spring:
  application:
    name: ai

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect
  #MySql
  # PORT 수정. 3306
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/noai?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: ssafy1234
    #password: root1234
jwt:
  expiration_time: 864000000
  secret: RElBUllfQU5EX0NPTU1VTklUWV9QUk9KRUNUX0RBV05BUllfQURNSU5fU0VDUkVUX0tFWQ==

api:
  maple:
    key: ${MAPLE_API_KEY}
    base-url: ${MAPLE_BASE_URL}

  wow:
    key: ${WOW_API_KEY}
    base-url: ${WOW_BASE_URL}

